server:
  port: 8080


logback:
  file: d:\\logs\\wen123
zhuangku:
  # 当次数据导出目录
  dataSourceDir: D:\\wen_test\\
  exportDir: d:\\export\\
  rateLimiterQps: 1
#  targetUrl: http://117.128.1.49:7011/recommendService/services/proQuery/102/004050160005/01/
  targetUrl: http://127.0.0.1:8080/test/

