server:
  port: 8080


logback:
  file: d:\\logs\\wen123
zhuangku:
  executeShellFlag: true
  shellFilePath: D:\\dir.bat
  # 解析后的文件目录
  cpRetDir: D:\\wen_test\\retDir\\
  dtpFilePrefix: access-8049-miguhui-pro.log-
  includeDataFileList: ["000000_0"]
  # 当次数据导出目录
  dataSourceDir: D:\\wen_test\\data\\
  exportDir: D:\\wen_test\\export\\
  rateLimiterQps: 100
  #  targetUrl: http://117.128.1.49:7011/recommendService/services/proQuery/102/004050160005/01/
  # targetUrl: http://127.0.0.1:8080/test/music/
  targetUrl: http://127.0.0.1:8080/test/video/
  #  targetUrl: http://127.0.0.1:8080/test/phone/
  readFileLimit: 100
  printFlag: 1000
  taskName: 'brand'
  readTimeout: 5000
  writeTimeout: 5000
  dayPeriodFile: migu_staff.txt
  rateLimiterQpsMap:
    0: 10
    1: 10
    2: 150
    3: 90
    4: 90
    5: 50
    6: 40
    7: 30
    8: 21
    9: 10
    10: 50
    11: 50
    12: 50
    13: 50
    14: 50
    15: 50
    16: 50
    17: 60
    18: 80
    19: 25
    20: 31
    21: 15
    22: 30
    23: 30




