server:
  port: 8080


logback:
  file: d:\\logs\\wen123
zhuangku:
  includeDataFileList: ["000000_0"]
  # 当次数据导出目录
  dataSourceDir: D:\\wen_test\\data\\
  exportDir: D:\\wen_test\\export\\
  rateLimiterQps: 100
  #  targetUrl: http://117.128.1.49:7011/recommendService/services/proQuery/102/004050160005/01/
  targetUrl: http://127.0.0.1:8080/test/header/
  readFileLimit: 100
  printFlag: 1000
  rateLimiterQpsMap:
    0: 200
    1: 200
    2: 150
    3: 90
    4: 90
    5: 50
    6: 40
    7: 30
    8: 21
    9: 10
    10: 500
    11: 500
    12: 500
    13: 500
    14: 500
    15: 500
    16: 500
    17: 60
    18: 80
    19: 250
    20: 310
    21: 150
    22: 300
    23: 300




