server:
  port: 80


logback:
  file: d:\\logs\\wen123

spring:
  thymeleaf:
    prefix: classpath:/static
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_plus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  typeAliasesPackage: com.wen.awenboot.domain
  mapper-locations:
    - classpath:mapper/*.xml

mala:
  appid: wx9de528650a768c77
  secret: db8368aa78a1945ff7bdfdbcb598489e



