server:
  port: 8080


logback:
  file: d:\\logs\\wen123

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

es:
  hosts: 127.0.0.1
  clusterName: elasticsearch
  index: migu_wen
  type: jh
zhuangku:
  #  esKey: offbehavior_video_60050
  showLog: false
  secretKey: MFZxY29UNjkxQ204OVgycXh1dDE3Nll1
  executeShellFlag: true
  dbFile: D:\\wen_test\\total.properties
  shellFilePath: D:\\dir.bat
  # 解析后的文件目录
  cpRetDir: D:\\wen_test\\retDir\\
  dtpFilePrefix: dtp_
  includeDataFileList: ["000000_0"]
  # 当次数据导出目录
  dataSourceDir: D:\\test1234\\
  exportDir: D:\\wen_test\\export\\
  rateLimiterQps: 100
  #  targetUrl: http://117.128.1.49:7011/recommendService/services/proQuery/102/004050160005/01/
  # targetUrl: http://127.0.0.1:8080/test/music/
  targetUrl: http://127.0.0.1:8080/test/video/
  #  targetUrl: http://127.0.0.1:8080/test/phone/
  readFileLimit: 10000
  printFlag: 1000
  taskName: 'es'
  readTimeout: 5000
  writeTimeout: 5000
  dayPeriodFile: migu_staff.txt
  rateLimiterQpsMap:
    0: 10





