server:
  port: 8080


logback:
  file: /data/malaxiaoyu/logs

spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: LEGACYHTML5
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.114.118.27:3306/springboot_plus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz@WSX
  redis:
    host: 47.114.118.27
    port: 6379
    password: redis123
    database: 0
    timeout: 10s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制） 太小可能出现connection.PoolExcelption
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）



mybatis:
  typeAliasesPackage: com.wen.awenboot.domain
  mapper-locations:
    - classpath:mapper/*.xml

mala:
  mockWechatCode: true
  appid: wx9de528650a768c77
  secret: db8368aa78a1945ff7bdfdbcb598489e



